-- TaskEase 完整数据库设置脚本
-- 在 Supabase SQL 编辑器中执行此脚本以完全重新设置数据库

-- 1. 删除现有表（如果存在）
DROP TABLE IF EXISTS public.user_preferences CASCADE;
DROP TABLE IF EXISTS public.todos CASCADE;
DROP TABLE IF EXISTS public.profiles CASCADE;

-- 2. 创建 profiles 表
CREATE TABLE public.profiles (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid NOT NULL UNIQUE REFERENCES auth.users(id) ON DELETE CASCADE,
  username text NOT NULL UNIQUE CHECK (char_length(username) >= 1 AND char_length(username) <= 15),
  created_at timestamptz NOT NULL DEFAULT now()
);

-- 3. 创建 todos 表
CREATE TABLE public.todos (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  title text NOT NULL CHECK (char_length(title) BETWEEN 1 AND 140),
  completed boolean NOT NULL DEFAULT false,
  user_id uuid NOT NULL DEFAULT auth.uid() REFERENCES auth.users(id) ON DELETE CASCADE,
  created_at timestamptz NOT NULL DEFAULT now()
);

-- 4. 创建 user_preferences 表
CREATE TABLE public.user_preferences (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid NOT NULL UNIQUE REFERENCES auth.users(id) ON DELETE CASCADE,
  theme_mode text NOT NULL DEFAULT 'system' CHECK (theme_mode IN ('light', 'dark', 'system')),
  language text NOT NULL DEFAULT 'zh-CN' CHECK (language IN ('zh-CN', 'zh-TW', 'en')),
  clock_format text NOT NULL DEFAULT '24h' CHECK (clock_format IN ('12h', '24h')),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

-- 5. 创建索引
CREATE INDEX IF NOT EXISTS profiles_user_id_idx ON public.profiles (user_id);
CREATE INDEX IF NOT EXISTS profiles_username_idx ON public.profiles (username);
CREATE INDEX IF NOT EXISTS todos_user_id_idx ON public.todos (user_id);
CREATE INDEX IF NOT EXISTS todos_created_at_idx ON public.todos (user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS user_preferences_user_id_idx ON public.user_preferences (user_id);

-- 6. 启用行级安全 (RLS)
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.todos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_preferences ENABLE ROW LEVEL SECURITY;

-- 7. 删除现有策略（如果存在）
DROP POLICY IF EXISTS "profiles_select_public" ON public.profiles;
DROP POLICY IF EXISTS "profiles_insert_own" ON public.profiles;
DROP POLICY IF EXISTS "profiles_update_own" ON public.profiles;
DROP POLICY IF EXISTS "profiles_select_own" ON public.profiles;

DROP POLICY IF EXISTS "todo_select_own" ON public.todos;
DROP POLICY IF EXISTS "todo_insert_own" ON public.todos;
DROP POLICY IF EXISTS "todo_update_own" ON public.todos;
DROP POLICY IF EXISTS "todo_delete_own" ON public.todos;

DROP POLICY IF EXISTS "user_preferences_select_own" ON public.user_preferences;
DROP POLICY IF EXISTS "user_preferences_insert_own" ON public.user_preferences;
DROP POLICY IF EXISTS "user_preferences_update_own" ON public.user_preferences;

-- 8. 创建新的 RLS 策略
-- profiles 表策略
CREATE POLICY "profiles_select_public" ON public.profiles FOR SELECT USING (true);
CREATE POLICY "profiles_insert_own" ON public.profiles FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "profiles_update_own" ON public.profiles FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "profiles_select_own" ON public.profiles FOR SELECT USING (auth.uid() = user_id);

-- todos 表策略
CREATE POLICY "todo_select_own" ON public.todos FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "todo_insert_own" ON public.todos FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "todo_update_own" ON public.todos FOR UPDATE USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
CREATE POLICY "todo_delete_own" ON public.todos FOR DELETE USING (auth.uid() = user_id);

-- user_preferences 表策略
CREATE POLICY "user_preferences_select_own" ON public.user_preferences FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "user_preferences_insert_own" ON public.user_preferences FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "user_preferences_update_own" ON public.user_preferences FOR UPDATE USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

-- 9. 创建更新时间的触发器
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ language 'plpgsql';

CREATE TRIGGER update_user_preferences_updated_at BEFORE UPDATE ON public.user_preferences
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- 10. 验证设置
COMMENT ON TABLE public.profiles IS '用户配置文件表';
COMMENT ON TABLE public.todos IS '任务表';
COMMENT ON TABLE public.user_preferences IS '用户偏好设置表';

-- 完成消息
SELECT '数据库设置完成！' AS message;