-- TaskEase: authenticated user isolation for todos + username profile
-- Run in Supabase SQL Editor

-- IMPORTANT
-- 1) Enable Email auth provider in Supabase.
-- 2) Turn OFF "Confirm email" so username/password can log in immediately.
-- 3) Frontend maps username to synthetic email: <username>@users.taskease.local.

create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id bigint generated by default as identity primary key,
  user_id uuid not null unique references auth.users(id) on delete cascade,
  username text not null unique check (char_length(username) >= 1 and char_length(username) <= 15),
  created_at timestamptz not null default now()
);

create index if not exists profiles_username_idx on public.profiles (username);

alter table public.profiles enable row level security;
alter table public.profiles force row level security;

create table if not exists public.todos (
  id uuid primary key default gen_random_uuid(),
  title text not null check (char_length(title) between 1 and 140),
  completed boolean not null default false,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

alter table public.todos add column if not exists user_id uuid references auth.users(id) on delete cascade;
alter table public.todos alter column user_id set default auth.uid();
create index if not exists todos_user_created_idx on public.todos (user_id, created_at desc);

alter table public.todos enable row level security;
alter table public.todos force row level security;

drop policy if exists "Allow read todos" on public.todos;
drop policy if exists "Allow insert todos" on public.todos;
drop policy if exists "Allow update todos" on public.todos;
drop policy if exists "Allow delete todos" on public.todos;
drop policy if exists "todo_select_own" on public.todos;
drop policy if exists "todo_insert_own" on public.todos;
drop policy if exists "todo_update_own" on public.todos;
drop policy if exists "todo_delete_own" on public.todos;
drop policy if exists "profiles_select_public" on public.profiles;
drop policy if exists "profiles_insert_own" on public.profiles;
drop policy if exists "profiles_update_own" on public.profiles;
drop policy if exists "profiles_select_own" on public.profiles;

create policy "profiles_select_public"
on public.profiles
for select
to anon, authenticated
using (true);

create policy "profiles_insert_own"
on public.profiles
for insert
to authenticated
with check (auth.uid() = user_id);

create policy "profiles_update_own"
on public.profiles
for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

create policy "profiles_select_own"
on public.profiles
for select
to authenticated
using (auth.uid() = user_id);

create policy "todo_select_own"
on public.todos
for select
to authenticated
using (auth.uid() = user_id);

create policy "todo_insert_own"
on public.todos
for insert
to authenticated
with check (auth.uid() = user_id);

create policy "todo_update_own"
on public.todos
for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

create policy "todo_delete_own"
on public.todos
for delete
to authenticated
using (auth.uid() = user_id);
