-- User preference table for TaskEase
-- Stores UI preferences per authenticated user

create table if not exists public.user_preferences (
  id bigint generated by default as identity primary key,
  user_id uuid not null unique references auth.users(id) on delete cascade,
  language text not null default 'zh-CN',
  clock_format text not null default '24h',
  theme_mode text not null default 'system',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint user_preferences_language_check check (language in ('zh-CN', 'zh-TW', 'en')),
  constraint user_preferences_clock_format_check check (clock_format in ('12h', '24h')),
  constraint user_preferences_theme_mode_check check (theme_mode in ('light', 'dark', 'system'))
);

create index if not exists user_preferences_user_id_idx on public.user_preferences(user_id);

create or replace function public.set_user_preferences_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_user_preferences_updated_at on public.user_preferences;
create trigger trg_user_preferences_updated_at
before update on public.user_preferences
for each row
execute function public.set_user_preferences_updated_at();

alter table public.user_preferences enable row level security;
alter table public.user_preferences force row level security;

drop policy if exists "user_preferences_select_own" on public.user_preferences;
drop policy if exists "user_preferences_insert_own" on public.user_preferences;
drop policy if exists "user_preferences_update_own" on public.user_preferences;
drop policy if exists "user_preferences_delete_own" on public.user_preferences;

create policy "user_preferences_select_own"
on public.user_preferences
for select
to authenticated
using (auth.uid() = user_id);

create policy "user_preferences_insert_own"
on public.user_preferences
for insert
to authenticated
with check (auth.uid() = user_id);

create policy "user_preferences_update_own"
on public.user_preferences
for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

create policy "user_preferences_delete_own"
on public.user_preferences
for delete
to authenticated
using (auth.uid() = user_id);
